### ISSUE TITLE
ValueError: Namespace Gdk not available

### ISSUE THREAD

**Issue by weiyiferonia** [NVlabs/few_shot_gaze#18]
I followed the "Realtime Demo Instructions" to run the demo, but found that:
          Traceback (most recent call last):
  File "run_demo.py", line 22, in <module>
    from monitor import monitor
  File "/home/rgyao/env/few_shot_gaze/demo/monitor.py", line 10, in <module>
    gi.require_version('Gdk', '3.0')
  File "/home/rgyao/anaconda3/envs/faze/lib/python3.6/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gdk not available

**Comment by allangu** [comment]
I was able to fix that part by install pgi (pip install pgi) and then adding the following two lines of code to the beginning of monitor.py

import pgi
pgi.install_as_gi()

**Comment by Leon-Brant** [comment]
> I was able to fix that part by install pgi (pip install pgi) and then adding the following two lines of code to the beginning of monitor.py
> 
> import pgi pgi.install_as_gi()

Do you run your code in ubuntu system?

**Comment by Leon-Brant** [comment]
> I followed the "Realtime Demo Instructions" to run the demo, but found that: Traceback (most recent call last): File "run_demo.py", line 22, in from monitor import monitor File "/home/rgyao/env/few_shot_gaze/demo/monitor.py", line 10, in gi.require_version('Gdk', '3.0') File "/home/rgyao/anaconda3/envs/faze/lib/python3.6/site-packages/gi/**init**.py", line 126, in require_version raise ValueError('Namespace %s not available' % namespace) ValueError: Namespace Gdk not available

Dude, how did you run `run_demo.py` in "Realtime Demo Instructions"? `run_demo.py` calls `frame_processor.py`, and `frame_processor.py` calls `detect_faces` and `show_bboxes` in the **src** folder. However, when I searched through the **src** folder and didn't find `detect_faces` or `show_bboxes`, I don't think the author's **src** folder is complete!
